export const Persons = [
  {
    'name': 'Imogene Shelton',
    'phone': '1-955-542-2755',
    'email': 'semper.pretium@nasceturridiculus.org',
    'address': 'Ap #749-3954 Non St.',
    'list': 3,
    'country': 'Belgium',
    'region': 'South Australia',
    'postalZip': '5302',
    'text': 'fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,',
    'numberrange': 0,
    'currency': '$53.54',
    'alphanumeric': 'BFG92CXS2YX',
  },
  {
    'name': 'Gay Mcgowan',
    'phone': '(726) 330-4567',
    'email': 'cum@quisquelibero.net',
    'address': '247-2383 Justo Av.',
    'list': 7,
    'country': 'Italy',
    'region': 'Punjab',
    'postalZip': '34738611',
    'text': 'vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci',
    'numberrange': 6,
    'currency': '$18.03',
    'alphanumeric': 'FFY15ZBG0JC',
  },
  {
    'name': 'Chandler Mcconnell',
    'phone': '1-209-374-7713',
    'email': 'vestibulum@intincidunt.co.uk',
    'address': '867-6820 Nec, Road',
    'list': 3,
    'country': 'Australia',
    'region': 'Limburg',
    'postalZip': '45-095',
    'text': 'nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante',
    'numberrange': 7,
    'currency': '$6.94',
    'alphanumeric': 'JMN70WCP1KJ',
  },
  {
    'name': 'Beverly Golden',
    'phone': '1-678-987-5172',
    'email': 'vivamus@sollicitudinadipiscing.co.uk',
    'address': 'P.O. Box 349, 3610 Mollis St.',
    'list': 5,
    'country': 'South Korea',
    'region': 'Amazonas',
    'postalZip': '66238',
    'text': 'luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi',
    'numberrange': 10,
    'currency': '$7.32',
    'alphanumeric': 'VRD75QDW8YM',
  },
  {
    'name': 'Courtney Mcdaniel',
    'phone': '1-232-529-2711',
    'email': 'dolor.quam.elementum@semeget.com',
    'address': '7574 Sed Ave',
    'list': 13,
    'country': 'India',
    'region': 'Khyber Pakhtoonkhwa',
    'postalZip': '7546',
    'text': 'Nullam velit dui, semper et, lacinia vitae, sodales at, velit.',
    'numberrange': 3,
    'currency': '$88.69',
    'alphanumeric': 'XXV46MIW5DS',
  },
  {
    'name': 'Candice Lyons',
    'phone': '1-254-825-2214',
    'email': 'massa@sodalespurusin.com',
    'address': '643-7253 Consectetuer Av.',
    'list': '7',
    'country': 'Chile',
    'postalZip': '9447',
    'region': 'Kujawsko-pomorskie',
    'text': 'id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus',
    'numberrange': '8',
    'currency': '$77.42',
    'alphanumeric': 'JCU47DXX2WF',
  },
  {
    'name': 'Reagan Fuller',
    'phone': '1-838-371-5976',
    'email': 'nam.ligula@augue.com',
    'address': '3849 Morbi Avenue',
    'list': '19',
    'country': 'Chile',
    'postalZip': '73832-81126',
    'region': 'Bryansk Oblast',
    'text': 'felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit',
    'numberrange': '8',
    'currency': '$25.78',
    'alphanumeric': 'JUE34KWS8QA',
  },
  {
    'name': 'Patricia Joyner',
    'phone': '1-354-499-7724',
    'email': 'tellus.aenean@tinciduntaliquam.edu',
    'address': '1266 Nec, Av.',
    'list': '11',
    'country': 'Austria',
    'postalZip': 'U6Y 8C1',
    'region': 'Nunavut',
    'text': 'Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae',
    'numberrange': '8',
    'currency': '$26.12',
    'alphanumeric': 'VEL56SBW2NH',
  },
  {
    'name': 'Myles Bright',
    'phone': '1-712-254-6832',
    'email': 'ut.molestie@mattis.com',
    'address': 'Ap #755-5870 Cum Ave',
    'list': '7',
    'country': 'Canada',
    'postalZip': '3261',
    'region': 'Pernambuco',
    'text': 'nunc nulla vulputate dui, nec tempus mauris erat eget ipsum.',
    'numberrange': '7',
    'currency': '$44.16',
    'alphanumeric': 'DUF52EOD0JJ',
  },
  {
    'name': 'Griffith Luna',
    'phone': '(586) 233-8092',
    'email': 'risus@ategestas.net',
    'address': '3114 Eleifend, Av.',
    'list': '5',
    'country': 'Peru',
    'postalZip': '75-585',
    'region': 'Kirov Oblast',
    'text': 'in faucibus orci luctus et ultrices posuere cubilia Curae Phasellus',
    'numberrange': '7',
    'currency': '$63.23',
    'alphanumeric': 'IGW10TNB7FX',
  },
  {
    'name': 'Kellie Burt',
    'phone': '1-273-797-7162',
    'email': 'nulla.eget@a.org',
    'address': 'P.O. Box 333, 4499 Lacinia Street',
    'list': '5',
    'country': 'Australia',
    'postalZip': '543347',
    'region': 'Dalarnas län',
    'text': 'Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede.',
    'numberrange': '2',
    'currency': '$88.64',
    'alphanumeric': 'MSZ94XDP4CY',
  },
  {
    'name': 'Mona Jefferson',
    'phone': '(319) 446-4613',
    'email': 'enim.etiam.imperdiet@vulputateullamcorpermagna.co.uk',
    'address': 'Ap #626-3432 Arcu. Rd.',
    'list': '1',
    'country': 'Costa Rica',
    'postalZip': '13783',
    'region': 'North Sulawesi',
    'text': 'mi tempor lorem, eget mollis lectus pede et risus. Quisque',
    'numberrange': '8',
    'currency': '$34.13',
    'alphanumeric': 'GTN46IRR6AW',
  },
  {
    'name': 'Clayton Neal',
    'phone': '1-322-285-3915',
    'email': 'lobortis.nisi@convallisconvallis.co.uk',
    'address': 'Ap #137-4512 Dui. Av.',
    'list': '15',
    'country': 'Netherlands',
    'postalZip': '8635',
    'region': 'Picardie',
    'text': 'mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam',
    'numberrange': '3',
    'currency': '$12.80',
    'alphanumeric': 'YSG23EGQ6HH',
  },
  {
    'name': 'Kenyon Mcguire',
    'phone': '1-192-332-1359',
    'email': 'risus.nunc@fuscedolorquam.ca',
    'address': '186-7613 Etiam Rd.',
    'list': '13',
    'country': 'Colombia',
    'postalZip': '31018',
    'region': 'Daman and Diu',
    'text': 'neque. Morbi quis urna. Nunc quis arcu vel quam dignissim',
    'numberrange': '4',
    'currency': '$78.74',
    'alphanumeric': 'AIQ74WSS8OB',
  },
  {
    'name': 'Ori Riggs',
    'phone': '1-925-866-8944',
    'email': 'vel.lectus.cum@ornaretortor.co.uk',
    'address': 'Ap #596-599 Amet Rd.',
    'list': '1',
    'country': 'Australia',
    'postalZip': '175412',
    'region': 'Newfoundland and Labrador',
    'text': 'sem mollis dui, in sodales elit erat vitae risus. Duis',
    'numberrange': '2',
    'currency': '$27.17',
    'alphanumeric': 'SVX81LVC4RV',
  },
]